2025-03-10 22:25:59,572 - ERROR - [20250310222559564] Uncaught exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1481, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 397, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-03-10 22:26:03,302 - ERROR - [20250310222559564] Exception caught by signal: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1481, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 397, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/handlers.py", line 75, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1218, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 679, in format
    if self.usesTime():
  File "/usr/local/lib/python3.10/logging/__init__.py", line 647, in usesTime
    return self._style.usesTime()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 424, in usesTime
    return self._fmt.find(self.asctime_search) >= 0
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1384, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 283, in _handle_exception
    return self.app.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1438, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 297, in _handle_server_error
    return self.app.handle_http_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/msnvsptt/mysite/flask_app.py", line 287, in _handle_server_error
    loggers['http'].error(
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/logging/handlers.py", line 77, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1021, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/bin/user_wsgi_wrapper.py", line 170, in write
    self.logger.error(line)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1612, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1554, in findCaller
    f = currentframe()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 160, in <lambda>
    currentframe = lambda: sys._getframe(3)
RecursionError: maximum recursion depth exceeded while calling a Python object

